version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
      - rabbitmq
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "run", "dev"]
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
      MESSAGE_QUEUE: amqp://rabbitmq
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
      - /app/node_modules

  worker:
    build:
      context: ./factory-worker
      #dockerfile: ./factory-worker/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      NODE_ENV: development
      PORT: 8080
      MESSAGE_QUEUE: amqp://rabbitmq
    ports:
      - "8080:8080"
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "npm", "run", "dev"]  
    #command: npm run dev
    volumes:
      - ./factory-worker:/worker/
      - /worker/node_modules
      
  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
      
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
